### ISSUE TITLE
Auto excluding VAC debugger tag when release phase

### ISSUE THREAD

**Issue by joey-yoonsung** [coxcore/react-vac#10]
Hi. I'm using the VAC pattern with this debugger.
Thanks to share the awesome tool.

Currently, I comment VAC component when I release my web FE application.

It would be good to automate excluding the VAC components before or during the build phase.

**Comment by coxcore** [comment]
@joey-yoonsung 
Thanks for the good comments. I'll try to figure out a way to automatically exclude it.

**Comment by coxcore** [comment]
Currently, it is impossible to completely remove the source code when using hidden properties, but it is possible to handle it so that it is not rendered.

```jsx
// global const
const production = true;

<VAC name="SomeVAC" data={SomeVACProps} hidden={production} />
```

https://github.com/coxcore/react-vac/blob/main/src/index.jsx#L20

**Comment by coxcore** [comment]
I've reviewed a few workarounds to your suggestion, but it's best to use `hidden` props.

There are too many patterns to consider to get rid of the debugger at the code level.

I also tried to remove only the debugger source with `tree shaking` from the bundle, but it was cumbersome to set up and had to add another module.

Close this issue. But I will keep thinking about this.
